# image: especifica uma imagem Docker pronta, seja local ou a ser baixada no Docker Hub;
# build: especifica a pasta contendo um arquivo Dockerfile a partir do qual o Compose vai executar o comando docker build automaticamente.
version: '3'
services:
  frontend:
    build: frontend/ # Especificamos o contexto, ou seja, a pasta onde está o Dockerfile.
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./logs:/var/log/frontend
    networks:
      - rede-virtual-1
  backend:
    build: backend/ # Especificamos o contexto, ou seja, a pasta onde está o Dockerfile.
    restart: always
    ports:
      - 3001:3001
      # o primeiro parâmetro é sempre a porta do computador local e o segundo parâmetro é a porta exposta no container.
    environment: # variáveis de ambiente
      - DB_HOST=database
    depends_on:
      - database
    networks:
      - rede-virtual-1
      - rede-virtual-2
  database:
    image: betrybe/docker-compose-example-database:v1 # Especificamos a Imagem Docker diretamente.
    restart: always
    volumes:
      - dados-do-banco:/data/db # Por que mapeamos o caminho "/data/db"? 🤔 como este banco de dados é um MongoDB, seus dados são armazenados nesta pasta específica, segundo sua documentação.
    networks:
      - rede-virtual-2

volumes:
  dados-do-banco:

networks:
  rede-virtual-1:
  rede-virtual-2:

# No final do arquivo existe uma nova chave de primeiro nível networks:
# Em cada linha declaramos o nome de uma nova rede virtual;
# As redes virtuais permitem criar isolamento entre os serviços;
# Ao utilizar esta chave, o Compose não vai mais criar a rede virtual padrão, como estava fazendo antes!
# Dentro de cada serviço, também temos a nova chave networks:
# Para o front-end, declaramos que ele está presente na rede-virtual-1;
# Para o back-end, declaramos que ele está presente na rede-virtual-2 e na rede-virtual-2;
# Para o database, declaramos que ele está presente na rede-virtual-2
