version: '3'
services:
  database:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trybecashdb
    ports:
      - "33061:3306"


# No arquivo docker-compose.yaml criado, foi definido um servi칞o chamado database. Esse servi칞o inicializar치 um container Docker com a imagem do Servidor MySQL vers칚o 8.0.29.

# O par칙metro restart define a pol칤tica de rein칤cio do container como always. Assim, o container sempre ser치 reiniciado automaticamente em caso de parada. Na se칞칚o environment foi definido o valor de duas vari치veis dentro do container:

# MYSQL_ROOT_PASSWORD: Essa vari치vel define a senha do usu치rio root do MySQL (ser치 a senha que utilizaremos para acessar o MySQL);
# MYSQL_DATABASE: Essa vari치vel define o nome do banco de dados que ser치 criado ao iniciar MySQL, caso o mesmo n칚o exista.
# J치 a se칞칚o ports est치 vinculando uma porta do seu computador local (a porta 33060) a uma porta dentro do container (a porta 3306).

# 丘멆잺 Aten칞칚o: estamos utilizando a porta 33060 como a porta vinculada ao seu computador local com o container MySQL, com a inten칞칚o de evitar um poss칤vel conflito de portas caso voc칡 possua uma instala칞칚o do MySQL em seu computador usando a porta 3306! 游땔